#!/usr/bin/env python3
"""Build the shipping ability files from the hub engine.

The DevKit ability and the cloud Skill each have to be ONE self-contained file — the
node server copies a single devkit_functions.py to the device, and the platform uploads
a single main.py. Until now that was done by hand, which meant hub/calc.py and the two
shipped copies were three files free to drift apart, with nothing checking they agreed.

This makes the hub the source and the shipped files the output:

    python3 hub/build_ability.py            # rewrite both artifacts
    python3 hub/build_ability.py --check    # fail if they are out of date (CI)

Only the region between the ENGINE markers is touched. The device wrapper, telemetry,
MQTT and capability classes around it are never rewritten.
"""
from __future__ import annotations
import ast
import pathlib
import subprocess
import sys

HUB = pathlib.Path(__file__).resolve().parent
REPO = HUB.parent

# (module, prefix) in ROUTING ORDER — engine.py last, it references the others.
MODULES = [
    ("mechanical", "mech"), ("calc", "calc"), ("study", "study"), ("chem", "chem"),
    ("sci", "sci"), ("stats", "stats"), ("mathx", "mathx"), ("engine", None),
]

BEGIN = "# ===== ASTRAL ENGINE — GENERATED BY hub/build_ability.py, DO NOT EDIT HERE ====="
END = "# ===== END ASTRAL ENGINE ====="

# Where the engine region starts and stops in each artifact, for the first build.
# (path, first-build start marker, first-build end marker, extra modules)
# comprehend backs the device-control path and belongs only in the DevKit file. The
# cloud Skill has no device to command, so shipping it there would be dead weight in
# the file that goes upstream. It was left out of the generator entirely at first,
# which meant a fix to hub/comprehend.py never reached the device — exactly the drift
# this generator exists to prevent, in the generator itself.
TARGETS = [
    ("community/astral/devkit_functions.py",
     "# ---------------- time / date (mechanical.py, inlined) ----------------",
     "# ============================ Astral device wrapper ============================",
     ["comprehend"]),
    ("community/astral-skill/main.py",
     "# ---------------- time / date (mechanical.py, inlined) ----------------",
     "# ============================ Astral capability ============================",
     []),
]
# Upstream layout. In openhome-dev/abilities this directory ships as
# community/astral/hub/ beside the one main.py the platform uploads, so there is a
# single target and it is the file next door. Same generator, same tests, either home.
if not (REPO / "community").is_dir() and (REPO / "main.py").is_file():
    TARGETS = [("main.py",
                "# ---------------- time / date (mechanical.py, inlined) ----------------",
                "# ============================ Astral capability ============================",
                [])]


def strip_module(name: str) -> str:
    """Module source with the parts that only make sense as a standalone file removed:
    its imports (the generated block declares them once), its docstring (kept as a
    comment banner), its ASR word list, and its __main__ demo."""
    src = (HUB / f"{name}.py").read_text()
    lines = src.splitlines()
    tree = ast.parse(src)
    drop = set()

    def kill(node):
        for i in range(node.lineno - 1, node.end_lineno):
            drop.add(i)

    doc = ast.get_docstring(tree, clean=False)
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            kill(node)
        elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) \
                and isinstance(node.value.value, str) and node is tree.body[0]:
            kill(node)
        elif isinstance(node, ast.If) and getattr(node.test.left, "id", "") == "__name__":
            kill(node)
        elif isinstance(node, ast.Assign) and any(
                getattr(t, "id", "") == "WORDS" for t in node.targets):
            kill(node)

    for i, line in enumerate(lines):
        if line.strip().startswith("#!") or "# INLINE-STRIP" in line:
            drop.add(i)

    body = "\n".join(line for i, line in enumerate(lines) if i not in drop).strip("\n")
    banner = [f"# ── {name}.py " + "─" * max(0, 68 - len(name))]
    if doc:
        banner += ["# " + d if d.strip() else "#" for d in doc.strip().splitlines()]
    return "\n".join(banner) + "\n" + body


def build_block(extra=()) -> str:
    parts = [BEGIN,
             "# Source: hub/{mechanical,calc,study,chem,sci,stats,mathx,engine}.py",
             "# Edit those and re-run `python3 hub/build_ability.py`. Hand edits here are lost.",
             "import math",
             "from fractions import Fraction",
             "from typing import Optional",
             ""]
    for name, prefix in MODULES:
        # Each body is formatted here, before splicing, so the artifact comes out the
        # same whether the sources on disk are dense (this repo) or were formatted on
        # the way upstream (community/astral/hub/). One artifact, either home.
        body = pep8(strip_module(name)).rstrip("\n")
        if prefix:
            body = body.replace("def handle(", f"def {prefix}_handle(")
        else:
            body = body.replace("def answer(", "def astral_answer(")
            for mod, pre in MODULES[:-1]:
                body = body.replace(f"{mod}.handle", f"{pre}_handle")
        parts += [body, ""]
    for name in extra:
        parts += [pep8(strip_module(name)).rstrip("\n"), ""]
    parts.append(END)
    return "\n".join(parts) + "\n"


def splice(path: pathlib.Path, start_mark: str, end_mark: str, block: str) -> str:
    text = path.read_text()
    lines = text.splitlines(keepends=True)
    begin = next((i for i, ln in enumerate(lines) if ln.startswith(BEGIN)), None)
    if begin is not None:
        # Re-build: the markers already delimit the region exactly, and the blank line
        # after END is outside it. Adding a separator here too grew the file by one
        # blank line on every run, so the generator was never idempotent and --check
        # reported STALE against its own output.
        finish = next(i for i, ln in enumerate(lines) if ln.startswith(END))
        sep = ""
    else:
        # First build: the region is the hand-inlined engine, and `finish` lands on the
        # blank line before the next section, so the separator has to be put back.
        begin = next(i for i, ln in enumerate(lines) if ln.startswith(start_mark))
        finish = next(i for i, ln in enumerate(lines) if ln.startswith(end_mark)) - 1
        sep = "\n"
    return "".join(lines[:begin]) + block + sep + "".join(lines[finish + 1:])


def pep8(text: str) -> str:
    """Format the artifact the way the upstream CI expects to find it.

    openhome-dev's lint job runs `flake8 --max-line-length=120 --ignore=E501,W503`,
    and the first build of this engine produced 575 violations, which would have turned
    an open PR red. The sources used to keep their unit tables dense and only the
    shipped files were formatted; since the sources ship upstream too (2026-09-01,
    community/astral/hub/) they are held to the same formatting, so the artifact comes
    out byte-identical whether it is built here or there.
    """
    try:
        import autopep8  # noqa: F401
    except ImportError:
        # Hard stop, not a warning. Without it the output differs from what is on disk,
        # so --check reports STALE forever and a plain build silently commits an
        # unformatted artifact that the upstream lint job then rejects. Both failures
        # point at the artifact instead of at the missing tool.
        raise SystemExit(
            "  autopep8 is required to build the shipped files and is not installed.\n"
            "  The artifacts are formatted on the way out because the upstream lint job\n"
            "  runs flake8 --ignore=E501,W503, which re-enables codes the default would\n"
            "  hide. Without it this build would produce a file that fails their CI.\n\n"
            "    python3 -m pip install autopep8\n")

    # The command line, not fix_code(): the two do not agree on E226, and the command
    # line is what the upstream job runs on the files it receives. Two passes. The
    # first is the general clean-up. The second exists because their --ignore=E501,W503
    # OVERRIDES pycodestyle's default ignore list, which switches E226 (spacing around
    # arithmetic operators) back on — and autopep8 will not touch E226 unless it is
    # explicitly selected. Selecting "E226" alone produces "x *2", which is worse than
    # leaving it; selecting the "E22" family produces "x * 2".
    def run(src: str, *args: str) -> str:
        return subprocess.run([sys.executable, "-m", "autopep8", "--max-line-length=120",
                               *args, "-"], input=src, capture_output=True, text=True,
                              check=True).stdout
    text = run(text, "--ignore=E501,W503", "--aggressive", "--aggressive")
    return run(text, "--select=E22", "--aggressive", "--aggressive")


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for rel, start_mark, end_mark, extra in TARGETS:
        path = REPO / rel
        new = pep8(splice(path, start_mark, end_mark, build_block(extra)))
        if new == path.read_text():
            print(f"  unchanged  {rel}")
            continue
        if check:
            stale.append(rel)
            print(f"  STALE      {rel}")
        else:
            path.write_text(new)
            print(f"  written    {rel}  ({len(new.splitlines())} lines)")
    if check and stale:
        print(f"\nFAIL — {len(stale)} artifact(s) out of date. Run: python3 hub/build_ability.py")
        return 1
    print("\nOK" if not check else "\nOK — artifacts match the hub")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
