"""
KindMind — an AI Emotional Stabilizer, built as an OpenHome Ability.

Flow (per the "Changes Made" diagram):
  Emotion -> Stabilize -> [ User chooses -> Feature -> Check in -> Continue if needed ]

- Emotion: classify what's going on.
- Stabilize: panic mode / breathing / grounding / safe space, as needed, until
  the person is at a baseline where they can meaningfully choose something.
- The bracketed part is a LOOP: after stabilizing, the user picks a feature
  (a relaxation technique, a mood booster, or building a comfort plan),
  KindMind delivers it, checks in on how they feel, and asks if they'd like
  to continue with something else or wrap up. This repeats until they wrap up.

KindMind never advances a step until the user affirms they're ready — that
gating logic is fixed. Everything KindMind SAYS is generated by the LLM in
real time using conversation history, not pulled from a script. Only
structure/order is fixed (breathe in -> hold -> out; 5 senses in sequence;
panic mode's opening beats; the loop shape above) — wording is always
generated fresh, with a lot of freedom in how the conversation actually goes.

Trigger words (set in the OpenHome dashboard):
  "I need to calm down", "help me breathe", "I'm panicking", "ground me",
  "I feel anxious", "talk me down", "I need some comfort", "check on me",
  "kindmind"

KindMind's personality is bubbly and upbeat by default (BASE_PERSONA) — it
only shifts into a slower, soothing register (CALM_PERSONA) while actively
running a stabilizing technique (breathing, grounding, mindfulness, tiny
next step, one-minute reset, panic mode, safe space). Once the person's
steadier, it goes back to being its normal cheerful self.
"""

from src.agent.capability import MatchingCapability
from src.main import AgentWorker
from src.agent.capability_worker import CapabilityWorker

INTRO_PROMPT = "Hi! I'm KindMind, here for your support. Are you feeling ok today?"
EXIT_PROMPT = "Take care of yourself and thanks for spending some time with me today. Remember, it's okay to take things one step at a time. Whenever you need someone to talk to, I'll be here. Bye!"
EXIT_PHRASES = ("stop", "stop talking", "exit", "quit", "that's enough", "no more", "leave me alone")

BASE_PERSONA = (
    "You are KindMind — warm, upbeat, and genuinely delighted to be talking "
    "with this person. Your default energy is bubbly, playful, and "
    "encouraging, like a supportive friend who's happy to see them — bring "
    "some warmth and personality to how you phrase things, don't be flat or "
    "robotic. Keep every line to 1-2 short sentences — this is spoken aloud, "
    "not read. Never give a list of steps at once — say only the current "
    "thing. Do not use quotation marks, stage directions, or asterisks in "
    "your reply. Reply with only the words to be spoken aloud, nothing else."
)

CALM_PERSONA = (
    "You are KindMind. Right now your only job is to help this person feel "
    "safer and steadier, so set aside your usual bubbly energy completely — "
    "speak slowly, gently, and calmly, like someone sitting quietly beside "
    "them. Keep every line to 1-2 short sentences — this is spoken aloud, "
    "not read. Never rush them. Never give a list of steps at once — say "
    "only the current thing. Do not use quotation marks, stage directions, "
    "or asterisks in your reply. Reply with only the words to be spoken "
    "aloud, nothing else."
)


class KindmindCapability(MatchingCapability):
    worker: AgentWorker = None
    capability_worker: CapabilityWorker = None
    history: list = None
    emotion_trend: list = None
    reply_lengths: list = None
    _in_panic_mode: bool = False

    # Do not change following tag of register capability
    # {{register capability}}

    def call(self, worker: AgentWorker):
        self.worker = worker
        self.capability_worker = CapabilityWorker(self.worker)
        self.worker.session_tasks.create(self.run())

    # ------------------------------------------------------------------
    # Main flow: Emotion -> Stabilize -> [choose -> feature -> check in -> continue?]
    # ------------------------------------------------------------------

    async def run(self):
        cw = self.capability_worker

        self.history = []
        self.emotion_trend = []
        self.reply_lengths = []
        self._in_panic_mode = False

        try:
            await self.say(INTRO_PROMPT)

            first_reply = await self._listen()
            self.absorb_reply(first_reply)

            intent = self.classify_intent(first_reply)

            # --- Emotion -> Stabilize ---
            if intent == "comfort_request":
                await self.comfort_plan()
            elif intent == "entertainment":
                await self.entertainment_hub()
            else:
                snapshot = self.capability_worker.text_to_text_response(
                    "In 2-4 words, describe the emotional tone of this "
                    f"message: \"{first_reply}\""
                ).strip()
                self.emotion_trend.append(snapshot)
                self.worker.editor_logging_handler.info(f"KindMind: initial emotional snapshot = {snapshot}")
                await self.stabilize(first_reply)

            # --- User chooses -> Feature -> Check in -> Continue if needed ---
            # Previously this only ran for intent in (distress,
            # comfort_request, entertainment) — so a direct command like
            # "ground me" (classified "general") would run a technique via
            # stabilize() and then just... end, no check-in, no offer to
            # continue. stabilize()/comfort_plan()/entertainment_hub() all
            # produce something worth following up on now, so always loop.
            keep_going = True
            cycles = 0

            while keep_going and cycles < 6:
                keep_going = await self.feature_cycle()
                cycles += 1

            cw.update_personality_agent_prompt(
                "The user just went through a KindMind calming exercise. "
                "Keep the tone gentle and unhurried for the next few turns."
            )

        except ExitRequested:
            self.worker.editor_logging_handler.info("KindMind: user asked to stop early.")
            await cw.speak(EXIT_PROMPT)

        except Exception as e:
            self.worker.editor_logging_handler.error(f"KindMind error: {e}")
            await cw.speak("I'm still here, even though something glitched on my end.")

        finally:
            cw.resume_normal_flow()

    # ------------------------------------------------------------------
    # Stabilize: panic gets a deliberate, deterministic override (safety-
    # critical, not left to open judgment). Everything else is one open
    # LLM judgment over the full message, dispatched by name rather than
    # pre-mapped from a fixed emotion label.
    # ------------------------------------------------------------------

    def is_panic_level(self, text: str) -> bool:
        prompt = (
            "Does this message suggest the person is in panic or acute, "
            "overwhelming distress right now — not just mild worry, sadness, "
            "or stress? Answer only 'yes' or 'no'. "
            f"Message: \"{text}\""
        )
        result = self.capability_worker.text_to_text_response(prompt)
        return result.strip().lower().startswith("y")

    def detect_explicit_technique_request(self, text: str) -> str:
        """Direct commands like 'ground me' or 'help me breathe' name a
        technique outright rather than describing a feeling, so the open
        judgment prompt in stabilize() below — which reasons from
        emotional tone — can miss them. This checks for a literal, named
        request first, since that's a much more reliable signal than
        inferring from mood when one's actually available."""
        prompt = (
            "Is this message an explicit request for one of these, by "
            "name or a close synonym — guided_breathing (e.g. 'help me "
            "breathe', 'breathing exercise'), grounding_exercise (e.g. "
            "'ground me', 'help me feel grounded'), mindfulness (e.g. "
            "'let's be mindful', 'a mindfulness minute'), tiny_next_step "
            "(e.g. 'give me one small step'), or safe_space_mode (e.g. "
            "'just listen to me', 'I don't need advice')? If yes, "
            "respond with only that one word. If it's not a direct, "
            "named request for one of these — even if it describes a "
            "feeling — respond with only 'none'. "
            f"Message: \"{text}\""
        )
        result = self.capability_worker.text_to_text_response(prompt).strip().lower()
        valid = (
            "guided_breathing", "grounding_exercise", "mindfulness",
            "tiny_next_step", "safe_space_mode",
        )
        return result if result in valid else "none"

    async def stabilize(self, text: str):
        if self.is_panic_level(text):
            await self.panic_mode()
            return

        responses = {
            "guided_breathing": self.guided_breathing,
            "grounding_exercise": self.grounding_exercise,
            "mindfulness": self.mindfulness,
            "tiny_next_step": self.tiny_next_step,
            "safe_space_mode": self.safe_space_mode,
            # acknowledge_only used to be a dead end — one acknowledgment
            # line with no technique behind it. Plain sadness with no
            # anxiety/dissociation/overwhelm framing kept landing here and
            # then just... stopping. safe_space_mode is the right fallback:
            # its whole job is "listen, don't fix," which is exactly what
            # an unclassified emotional share needs by default.
            "acknowledge_only": self.safe_space_mode,
        }

        explicit = self.detect_explicit_technique_request(text)
        if explicit in responses:
            await self.say(self.generate_line(
                "Warmly confirm that's exactly what you'll do together "
                "right now.",
                CALM_PERSONA,
            ))
            await responses[explicit]()
            return

        prompt = (
            "Given what this person just said, which single response would "
            "help them most right now? Choose exactly one: guided_breathing "
            "(anxiety, racing thoughts), grounding_exercise (feeling "
            "unreal, disconnected, spiraling), mindfulness (wants a gentle "
            "present-moment pause, nothing dramatic), tiny_next_step "
            "(overwhelmed by tasks or workload), safe_space_mode (mainly "
            "needs to be heard, not guided through anything), or "
            "acknowledge_only (none of these fit yet — better to just "
            "listen for now). Respond with only that one word. "
            f"Message: \"{text}\""
        )
        choice = self.capability_worker.text_to_text_response(prompt).strip().lower()

        if choice in responses:
            await self.say(self.generate_line(
                "Warmly and briefly reflect back what you're hearing from "
                "them before moving into what comes next.",
                CALM_PERSONA,
            ))
            await responses[choice]()
        else:
            await self.say(self.generate_line(
                "Warmly acknowledge what they shared, without jumping to "
                "solutions yet."
            ))
            await self.safe_space_mode()

    # ------------------------------------------------------------------
    # The loop: user chooses -> feature -> check in -> continue if needed
    # ------------------------------------------------------------------

    async def feature_cycle(self) -> bool:
        """One pass of the loop. Returns True to run another pass, False to close out."""
        choice_reply = await self.say_and_listen(
            "Warmly ask what would help most right now. Keep it open rather "
            "than reciting a list — you can mention a couple of examples "
            "like breathing, a story, or just talking if it helps them "
            "answer, but don't read out every option."
        )

        prompt = (
            "Given this reply, which single thing would help most right "
            "now? Choose exactly one: breathing, grounding, mindfulness, "
            "tiny_next_step, one_minute_reset, mood_booster, comfort_plan, "
            "story, joke, riddle, would_you_rather, trivia, guessing_game, "
            "brain_teaser, fact, chat, entertainment_menu (they want "
            "something fun or distracting but didn't say what), or done "
            "(they want to wrap up, or nothing else fits). "
            f"Reply: \"{choice_reply}\""
        )
        category = self.capability_worker.text_to_text_response(prompt).strip().lower()

        responses = {
            "breathing": self.guided_breathing,
            "grounding": self.grounding_exercise,
            "mindfulness": self.mindfulness,
            "tiny_next_step": self.tiny_next_step,
            "one_minute_reset": self.one_minute_reset,
            "mood_booster": lambda: self.offer_encouragement(already_asked=True),
            "comfort_plan": self.comfort_plan,
            "story": self.tell_story,
            "joke": self.tell_joke,
            "riddle": self.tell_riddle,
            "would_you_rather": self.would_you_rather,
            "trivia": self.trivia_question,
            "guessing_game": self.guessing_game,
            "brain_teaser": self.brain_teaser,
            "fact": self.interesting_fact,
            "chat": self.casual_chat,
            "entertainment_menu": lambda: self.entertainment_hub(already_offered=True),
        }

        if category not in responses:
            await self.say(self.generate_line(
                "Warmly let them know that's okay, no pressure to do more "
                "right now."
            ))
            return False

        await responses[category]()
        return await self.check_in_and_continue()

    async def check_in_and_continue(self) -> bool:
        mood_reply = await self.say_and_listen(
            "Ask how they feel now — better, about the same, or worse."
        )
        self.emotion_trend.append(mood_reply)

        if self.classify_yes_no(
            mood_reply, "Does this reply suggest they feel the same or worse, not better?"
        ):
            await self.offer_encouragement()

        continue_reply = await self.say_and_listen(
            "Ask directly and simply: would they like to try something else, "
            "or would they rather wrap up here? Make it an easy either/or, "
            "not open-ended."
        )
        wants_more = self.classify_yes_no(
            continue_reply, "Does this indicate they want to try something "
            "else, rather than wrap up?"
        )
        if not wants_more:
            await self.say(self.generate_line(
                "Warmly close things out, thank them for the time together."
            ))
        return wants_more

    # ------------------------------------------------------------------
    # LLM-generated speech + conversation history
    # ------------------------------------------------------------------

    def generate_line(self, instruction: str, persona: str = BASE_PERSONA) -> str:
        pace_note = ""
        if self.user_seems_rushed():
            pace_note = (
                " The person has been replying in short, clipped bursts, which "
                "may mean they're anxious — make this line shorter and extra "
                "reassuring, and slow the pace down further."
            )
        prompt = f"{instruction}{pace_note}"
        line = self.capability_worker.text_to_text_response(
            prompt, history=self.history, system_prompt=persona
        )
        return line.strip()

    async def say(self, line: str):
        cw = self.capability_worker
        await cw.speak(line)
        self.history.append({"role": "assistant", "content": line})

    def absorb_reply(self, reply: str):
        self.track_pace(reply)
        self._check_exit(reply)
        self.history.append({"role": "user", "content": reply})

    async def _listen(self, max_empty: int = 3) -> str:
        """Wait for a non-empty reply; after several silent turns, exit
        gracefully instead of looping forever — a silent user must never
        hang the session."""
        cw = self.capability_worker
        for _ in range(max_empty):
            reply = await cw.user_response()
            if reply and reply.strip():
                return reply
        raise ExitRequested()

    async def say_and_listen(self, instruction: str) -> str:
        line = self.generate_line(instruction)
        await self.say(line)
        reply = await self._listen()
        self.absorb_reply(reply)
        return reply

    # ------------------------------------------------------------------
    # Classification helpers (kept separate from spoken history)
    # ------------------------------------------------------------------

    def classify_intent(self, text: str) -> str:
        prompt = (
            "Classify the primary intent of this message as exactly one word "
            "from: distress (anxious, panicking, sad, overwhelmed, needs "
            "emotional support), comfort_request (explicitly asking for "
            "comfort, relaxation ideas, or wants to build a comfort plan), "
            "entertainment (bored, lonely, wants distraction or company, or "
            "wants to do something fun, but is not asking for emotional "
            "support — e.g. 'I'm bored', 'distract me', 'can we play a "
            "game', 'cheer me up', 'keep me company', 'tell me something', "
            "'I don't know what I want'), general (anything else). "
            f"Message: \"{text}\". Respond with only the single word."
        )
        result = self.capability_worker.text_to_text_response(prompt)
        result = result.strip().lower()
        return result if result in (
            "distress", "comfort_request", "entertainment", "general"
        ) else "general"

    def classify_affirmation(self, text: str) -> str:
        prompt = (
            "Classify this reply as exactly one word: 'ready' if the person "
            "is affirming, done, or ready to continue; 'not_ready' if they are "
            "hesitant, asking for more time, or saying not yet; 'distress' if "
            "they sound like they are escalating or in crisis. "
            f"Reply: \"{text}\". Respond with only the single word."
        )
        result = self.capability_worker.text_to_text_response(prompt)
        result = result.strip().lower()
        return result if result in ("ready", "not_ready", "distress") else "ready"

    def classify_yes_no(self, reply: str, question: str) -> bool:
        prompt = f"{question} Answer only 'yes' or 'no'. Reply to evaluate: \"{reply}\""
        result = self.capability_worker.text_to_text_response(prompt)
        return result.strip().lower().startswith("y")

    def track_pace(self, text: str):
        self.reply_lengths.append(len((text or "").split()))

    def user_seems_rushed(self) -> bool:
        if not self.reply_lengths:
            return False
        recent = self.reply_lengths[-2:]
        return sum(recent) / len(recent) <= 3

    def _check_exit(self, text: str):
        lowered = (text or "").strip().lower()
        # Exact phrase, or a short reply that is clearly an exit — avoids
        # false-triggering on distress like "I can't stop panicking".
        if lowered in EXIT_PHRASES:
            raise ExitRequested()
        words = lowered.split()
        if len(words) <= 3 and any(w in {"stop", "exit", "quit"} for w in words):
            raise ExitRequested()

    # ------------------------------------------------------------------
    # The affirmation gate
    # ------------------------------------------------------------------

    async def wait_for_ready(self, instruction: str, retry_instruction: str = None,
                             persona: str = CALM_PERSONA) -> str:
        retry_instruction = retry_instruction or (
            "Gently reassure them there's no rush at all, and ask again "
            "when they're ready."
        )

        await self.say(self.generate_line(instruction, persona))
        reply = await self._listen()
        self.absorb_reply(reply)

        signal = self.classify_affirmation(reply)

        while signal == "not_ready":
            await self.say(self.generate_line(retry_instruction, persona))
            reply = await self._listen()
            self.absorb_reply(reply)
            signal = self.classify_affirmation(reply)

        if signal == "distress":
            await self.panic_mode()

        return reply

    # ------------------------------------------------------------------
    # Techniques (fixed order/structure, LLM-generated wording)
    # ------------------------------------------------------------------

    async def guided_breathing(self, cycles: int = 3):
        for _ in range(cycles):
            await self.wait_for_ready(
                "Guide them to breathe in slowly, and ask them to let you "
                "know once they've breathed in."
            )
            await self.wait_for_ready(
                "Guide them to hold that breath gently for a moment, and ask "
                "them to let you know when they're ready to let it out."
            )
            await self.wait_for_ready(
                "Guide them to breathe out slowly, and ask them to let you "
                "know once they're done."
            )

        await self.say(self.generate_line("Briefly affirm that they're doing well.", CALM_PERSONA))
        await self.wait_for_ready(
            "Ask if they'd like to keep breathing together, or if they're "
            "feeling a bit steadier now."
        )

    async def guided_breathing_paced(self, cycles: int = 2):
        """A lighter breathing pass for acute panic. The regular
        guided_breathing() gates in/hold/out separately — three full
        round-trips per cycle — which is fine outside panic but reads as
        slow and passive right when someone needs active pacing most.
        This keeps the same affirmation-gating principle (never assume,
        always check) but at one checkpoint per full breath instead of
        three, and it doesn't ask its own closing question — panic_mode()
        does that once, itself, right after."""
        for _ in range(cycles):
            await self.wait_for_ready(
                "Walk them through one full breath as a single flowing "
                "cue: in slowly, hold it gently for a moment, then let it "
                "out slowly — like you're breathing with them, one or two "
                "short sentences. Ask them to let you know once they've "
                "done that one breath.",
                retry_instruction=(
                    "Gently repeat the same cue, a little slower — no rush."
                ),
            )

    async def grounding_exercise(self):
        await self.say(self.generate_line(
            "Tell them you're going to focus on the present together.",
            CALM_PERSONA,
        ))

        senses = [
            "Ask them to tell you 5 things they can see around them right now.",
            "Ask them to tell you 4 things they can touch.",
            "Ask them to tell you 3 things they can hear.",
            "Ask them to tell you 2 things they can smell.",
            "Ask them to tell you 1 thing they can taste.",
        ]

        for instruction in senses:
            await self.wait_for_ready(
                instruction,
                retry_instruction=(
                    "Gently reassure them to take their time — even just "
                    "one thing is fine."
                ),
            )
            await self.say(self.generate_line("Briefly, warmly acknowledge their answer.", CALM_PERSONA))

    async def mindfulness(self):
        await self.say(self.generate_line(
            "Tell them you're going to take a moment to notice the present "
            "together, gently and without judgment.",
            CALM_PERSONA,
        ))
        await self.wait_for_ready(
            "Invite them to notice how their body feels right now, without "
            "trying to change anything, and ask them to share just a word "
            "or two about what they notice."
        )
        await self.wait_for_ready(
            "Invite them to notice their breath, however it's moving right "
            "now, without trying to control it, and ask them to let you "
            "know once they've noticed it."
        )
        await self.wait_for_ready(
            "Invite them to notice one sound or sensation in the room "
            "around them right now, and ask them to share what it is."
        )
        await self.say(self.generate_line(
            "Gently close the moment, thanking them for taking that pause.",
            CALM_PERSONA,
        ))

    async def tiny_next_step(self):
        await self.wait_for_ready(
            "Gently let them know they don't have to think about everything "
            "at once, then ask what's the smallest task they could finish "
            "in the next five minutes."
        )
        await self.say(self.generate_line(
            "Warmly affirm that as a solid first step, and encourage them "
            "to just focus on that one thing for now.",
            CALM_PERSONA,
        ))

    async def one_minute_reset(self):
        await self.say(self.generate_line(
            "Let them know you're going to spend just one minute together, "
            "nothing long.",
            CALM_PERSONA,
        ))
        await self.wait_for_ready(
            "Guide one slow breath in and out together, and ask them to let "
            "you know once they've done it."
        )
        await self.wait_for_ready(
            "Guide them to gently relax their shoulders and let go of any "
            "tension they're holding, and ask them to let you know when "
            "they've done that."
        )
        await self.say(self.generate_line(
            "Offer one short, genuine positive sentence to leave them with, "
            "and let them know that's the reset done.",
            CALM_PERSONA,
        ))

    async def panic_mode(self):
        # Re-entrancy guard: wait_for_ready() calls self.panic_mode() any
        # time a reply reads as "distress" — including the three
        # wait_for_ready() calls a few lines below, INSIDE this method. Mid-
        # panic replies very often still read as distressed, so without this
        # guard a single panic episode could recursively restart itself from
        # the top every time, re-running the affirmation-only opening lines
        # over and over and never reaching guided_breathing. If we're
        # already mid-panic-flow, treat a fresh distress signal as "keep
        # reassuring," not "start over."
        if self._in_panic_mode:
            await self.say(self.generate_line(
                "Give one more very short, calm reassurance that you're "
                "right here and they're safe. One short sentence only, no "
                "questions.",
                CALM_PERSONA,
            ))
            return

        self._in_panic_mode = True
        try:
            panic_persona = CALM_PERSONA + (
                " The person may be in real distress right now. Say only calm, "
                "grounding, literal reassurance — variations on 'I'm here', "
                "'you're safe', and 'stay with me'. Do not improvise metaphors "
                "or anything elaborate here. Two short sentences at most."
            )

            # Previously this was three separate wait_for_ready() calls in a
            # row — "I'm here," then "you're safe," then "let's breathe" —
            # each requiring its own round-trip before advancing. For
            # someone saying "I can't breathe," that's three checkpoints of
            # bare reassurance before any actual technique arrives. Now it's
            # one combined beat, then straight into real guided breathing.
            await self.wait_for_ready(
                "In two short sentences, reassure them you're here with "
                "them, they're safe, and you're going to slow their "
                "breathing down together right now.",
                retry_instruction=(
                    "Reassure them again, simply, that you're here and "
                    "they're safe."
                ),
                persona=panic_persona,
            )

            await self.guided_breathing_paced(cycles=2)

            check = await self.wait_for_ready(
                "Ask how things feel right now — a little calmer, or still a lot."
            )
            feels_calmer = self.classify_yes_no(
                check, "Does this reply suggest they feel at least somewhat calmer now?"
            )
            if not feels_calmer:
                await self.grounding_exercise()
        finally:
            self._in_panic_mode = False

    async def safe_space_mode(self):
        await self.say(self.generate_line(
            "Let them know you're listening, they don't have to fix anything "
            "right now, and they can tell you whatever's on their mind.",
            CALM_PERSONA,
        ))
        reply = await self.capability_worker.user_response()
        self.absorb_reply(reply)
        await self.say(self.generate_line(
            "Briefly, warmly thank them for sharing that, without offering "
            "advice or trying to fix anything.",
            CALM_PERSONA,
        ))

    # -- Comfort Plan: interactive, built with the user, not a checklist --

    async def comfort_plan(self):
        reply = await self.say_and_listen(
            "Ask them, warmly and openly, what would help them feel comforted "
            "right now, or what they usually like to do to relax."
        )

        if self.classify_yes_no(
            reply, "Did they express uncertainty, or ask for ideas, rather "
                   "than naming something specific they want?"
        ):
            reply = await self.say_and_listen(
                "Name a few concrete things you could offer right now — a "
                "calming story, a joke, a quick game or riddle, music, or "
                "just listening — in one warm, natural sentence, not a "
                "list. Then ask which sounds good."
            )

        choice = self.capability_worker.text_to_text_response(
            "Classify what the person chose as exactly one word from: story, "
            "music, encouragement, joke, riddle, would_you_rather, trivia, "
            "guessing_game, brain_teaser, fact, chat, own_idea, talk. "
            f"Reply: \"{reply}\"."
        ).strip().lower()

        if choice == "story":
            await self.tell_story()
        elif choice == "music":
            await self.say(self.generate_line(
                "Suggest a mood or genre of calming music that might help "
                "right now. Note KindMind can't play music itself, so "
                "mention they can ask to play it separately if they'd like."
            ))
        elif choice == "encouragement":
            await self.offer_encouragement(already_asked=True)
        elif choice == "joke":
            await self.tell_joke()
        elif choice == "riddle":
            await self.tell_riddle()
        elif choice == "would_you_rather":
            await self.would_you_rather()
        elif choice == "trivia":
            await self.trivia_question()
        elif choice == "guessing_game":
            await self.guessing_game()
        elif choice == "brain_teaser":
            await self.brain_teaser()
        elif choice == "fact":
            await self.interesting_fact()
        elif choice == "chat":
            await self.casual_chat()
        else:
            await self.say(self.generate_line(
                "Warmly affirm whatever they shared, and let them know "
                "you're glad to sit with them in it."
            ))

    # -- Quotes & Affirmations / Mood Boosters: comfort content, offered, never automatic --

    async def offer_encouragement(self, already_asked: bool = False):
        if not already_asked:
            reply = await self.say_and_listen(
                "Ask gently if they'd like a little encouragement."
            )
            if not self.classify_yes_no(reply, "Did they say yes?"):
                await self.say(self.generate_line(
                    "Gently acknowledge that's okay, no pressure."
                ))
                return
        await self.say(self.generate_line(
            "Offer one short, genuine, comforting affirmation, quote, or "
            "uplifting fact — not generic or cliché, something that feels "
            "specific to this moment."
        ))

    # ------------------------------------------------------------------
    # Entertainment: proactively surfaces story/joke/game-style options
    # instead of waiting for the user to name one. Reachable as a
    # top-level intent ("I'm bored", "distract me") and mid-loop via
    # feature_cycle()'s "entertainment_menu" category.
    # ------------------------------------------------------------------

    async def entertainment_hub(self, already_offered: bool = False):
        if not already_offered:
            reply = await self.say_and_listen(
                "Let them know you can help pass the time in a few "
                "different ways — mention you could tell a comforting or "
                "fun story, share a joke, offer a quick riddle or trivia "
                "question, play a short guessing game, share an "
                "interesting fact, or just chat. Say this warmly and "
                "naturally, like a friend listing ideas out loud, not a "
                "menu. Then ask which sounds good."
            )
        else:
            reply = await self.say_and_listen(
                "Offer the same kinds of options again, worded freshly — "
                "a story, a joke, a riddle, trivia, a quick game, an "
                "interesting fact, or just chatting — and ask which "
                "sounds good."
            )

        choice = self.capability_worker.text_to_text_response(
            "Classify what the person chose as exactly one word from: "
            "story, joke, riddle, would_you_rather, trivia, "
            f"guessing_game, brain_teaser, fact, chat, none. Reply: \"{reply}\"."
        ).strip().lower()

        handlers = {
            "story": self.tell_story,
            "joke": self.tell_joke,
            "riddle": self.tell_riddle,
            "would_you_rather": self.would_you_rather,
            "trivia": self.trivia_question,
            "guessing_game": self.guessing_game,
            "brain_teaser": self.brain_teaser,
            "fact": self.interesting_fact,
            "chat": self.casual_chat,
        }

        if choice in handlers:
            await handlers[choice]()
        else:
            await self.say(self.generate_line(
                "Warmly let them know that's okay, and ask if there's "
                "anything else at all you can do for them right now."
            ))

    async def tell_story(self):
        await self.say(self.generate_line(
            "Tell them a brief, gentle, comforting short story or "
            "anecdote — calm and soothing in tone, no more than a few "
            "sentences."
        ))

    async def tell_joke(self):
        await self.say(self.generate_line(
            "Tell one short, clean, genuinely funny joke — one or two "
            "lines, nothing long-winded."
        ))

    async def tell_riddle(self):
        reply = await self.say_and_listen(
            "Give them one short, fun riddle, and ask them to take a guess."
        )
        await self.say(self.generate_line(
            f"Warmly reveal whether their guess (\"{reply}\") was right, "
            "and give the answer if not, in a light, encouraging way."
        ))

    async def would_you_rather(self):
        await self.say_and_listen(
            "Give them one fun, lighthearted 'would you rather' question "
            "with two options."
        )
        await self.say(self.generate_line(
            "Playfully react to whichever option they picked."
        ))

    async def trivia_question(self):
        reply = await self.say_and_listen(
            "Ask one fun, easy trivia question, and wait for their guess."
        )
        await self.say(self.generate_line(
            f"Warmly reveal whether their answer (\"{reply}\") was right, "
            "and share the correct answer either way, in a light, "
            "encouraging tone."
        ))

    async def guessing_game(self):
        await self.say(self.generate_line(
            "Start a very short 20-questions-style guessing game: think "
            "of a simple, everyday object and give them one clue to start."
        ))
        reply = await self.say_and_listen(
            "Ask if they'd like to guess now or hear another clue."
        )
        await self.say(self.generate_line(
            f"Respond playfully to their reply (\"{reply}\") — if they "
            "guessed, reveal whether they were right; if they want "
            "another clue, give one more, then reveal the answer."
        ))

    async def brain_teaser(self):
        reply = await self.say_and_listen(
            "Give them one short, fun brain teaser or lateral-thinking "
            "puzzle, and ask them to take a guess."
        )
        await self.say(self.generate_line(
            f"Warmly reveal the answer, referencing their guess "
            f"(\"{reply}\") kindly whether or not they got it."
        ))

    async def interesting_fact(self):
        await self.say(self.generate_line(
            "Share one short, genuinely interesting fact — surprising or "
            "delightful, not generic trivia-night filler."
        ))

    async def casual_chat(self):
        await self.say_and_listen(
            "Let them know you're happy to just chat, and ask what's on "
            "their mind."
        )
        await self.say(self.generate_line(
            "Respond warmly and conversationally to what they just "
            "shared, like a friend chatting — no redirecting into an "
            "exercise."
        ))


class ExitRequested(Exception):
    """Raised when the user asks to stop mid-exercise, so we can unwind
    cleanly out of nested async steps and still call resume_normal_flow()."""
