"""Fart2Fart(coin) background daemon (cloud side).

Starts at session begin. Runs the consent check once, starts the device
listener, then polls it every POLL_INTERVAL_S. Each new event is announced in
the emergency-broadcast voice after send_interrupt_signal(), then hooks run.
The `buy` hook swaps a whole number of dollars of USDC into Fartcoin through
the Bankr Wallet API with no confirmation step. Spend limits are Bankr's
(bankr.bot -> Security); this daemon only guards against double-buys.

Trading state (mode, buy_usd, route, journal) is shared with main.py through
the KV store under CONTEXT_KEY. A fresh install is in dry_run until the user
says "turn fart trading on".

Device transport is selected by the `fartfinder_transport` setting:
    devkit  (default)  send_devkit_capability_action -> devkit_functions.py on the Pi
    local              exec_local_command -> devkit_functions.py on a Mac via `openhome local`
For local, `fartfinder_local_cmd` must be the absolute command prefix, e.g.
    /Users/me/openhome-fart2fart/.venv/bin/python /Users/me/openhome-fart2fart/abilities/user/fart2fart/devkit_functions.py
"""
import asyncio
import json
from time import time

from src.agent.capability import MatchingCapability
from src.main import AgentWorker
from src.agent.capability_worker import CapabilityWorker

import re
import uuid
from decimal import Decimal, ROUND_DOWN, InvalidOperation

import requests

POLL_INTERVAL_S = 1.5
DEVICE_TIMEOUT_S = 8
LOCAL_TIMEOUT_S = 6.0
SETTINGS_FILE = "settings.local.json"
RESTART_BACKOFF_S = 15.0
CONTEXT_KEY = "fart2fartcoin"

ONES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]

CLASS_LINES = {
    "whisper": ("Minor event detected.", "Probably deniable."),
    "squeak": ("Localised event detected.", "No action required."),
    "standard-issue": ("Warning. Fart detected.", "Be on smell lookout."),
    "notable": ("Warning. Notable event detected.", "Be on smell lookout."),
    "room-clearing": ("Warning. Room-clearing event detected.", "Open a window and be on smell lookout."),
    "structural": ("Warning. Structural event detected.", "Check on the dog."),
    "evacuate": ("Warning. Evacuate the vicinity.", "This is not a drill."),
    "biblical": ("Warning. A magnitude nine event.", "Records have been kept."),
}

NOT_ARMED_NOTICE = ("Fart2Fart(coin) is installed but not armed. It listens to this room continuously; audio "
                    "never leaves the device and nothing is stored. Say fart finder, arm, to turn it on. "
                    "Buying is off until you say turn fart trading on.")
DRY_RUN_LINE = "Dry run. That would have bought %s of Fartcoin, %s."
DRY_RUN_NO_QUOTE = "Dry run. That would have bought %s of Fartcoin."
BOUGHT_LINE = "Bought %s of Fartcoin, %s."
LANDED_LATE_LINE = "The Fartcoin from that last fart has landed."
NOT_LANDED_LINE = "The Fartcoin from that last fart has not landed yet. Check bankr dot bot."
DAILY_LINE = "Yesterday: %s."
CONSENT_POLL_S = 10.0


# ---- begin trade.py (generated by tools/inline_trade.py; edit trade.py, not this) ----
BANKR_API = "https://api.bankr.bot"
READ_KEY_NAME = "bankr_read_key"
TRADE_KEY_NAME = "bankr_trade_key"

FARTCOIN_MINT = "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump"      # Solana, 6 decimals
USDC_BASE = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"            # Base, 6 decimals
USDC_SOLANA = "EPjFWaLb3hycctiUiZXEXUoahKUhbSooLesGa3ApL2f"         # Solana, 6 decimals
FARTCOIN_DECIMALS = 6

ROUTES = {
    "base_to_solana": {"fromChain": "base", "fromToken": USDC_BASE, "toChain": "solana", "toToken": FARTCOIN_MINT},
    "solana": {"fromChain": "solana", "fromToken": USDC_SOLANA, "toChain": "solana", "toToken": FARTCOIN_MINT},
}
DEFAULT_ROUTE = "base_to_solana"

DEFAULT_BUY_USD = 1
DEFAULT_SLIPPAGE_BPS = 300
MIN_SLIPPAGE_BPS, MAX_SLIPPAGE_BPS = 10, 2000

QUOTE_TIMEOUT_S = 15
SWAP_TIMEOUT_S = 120          # cross-chain fills take longer than same-chain
PORTFOLIO_TIMEOUT_S = 12

ARRIVAL_CHECK_EVERY_S = 30
ARRIVAL_WINDOW_S = 10 * 60
JOURNAL_MAX = 200

_EVM_ADDR_RE = re.compile(r"^0x[0-9a-fA-F]{40}$")
_BASE58_RE = re.compile(r"^[1-9A-HJ-NP-Za-km-z]{32,44}$")


# -----------------------------------------------------------------------------
# Amount parsing: whole dollars only
# -----------------------------------------------------------------------------

_ONES = {
    "zero": 0, "oh": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11,
    "twelve": 12, "thirteen": 13, "fourteen": 14, "fifteen": 15, "sixteen": 16,
    "seventeen": 17, "eighteen": 18, "nineteen": 19,
}
_TENS = {
    "twenty": 20, "thirty": 30, "forty": 40, "fifty": 50, "sixty": 60,
    "seventy": 70, "eighty": 80, "ninety": 90,
}
_SCALES = {"hundred": 100, "thousand": 1000}
_FILLER = {
    "dollars", "dollar", "bucks", "buck", "usd", "us", "of", "to", "a", "the",
    "please", "set", "my", "fart", "buy", "amount", "per", "each", "every",
    "is", "it", "at", "make", "um", "uh", "so", "that", "and",
}
_ARTICLE_ONE = {"a", "one"}


def _words_to_number(tokens):
    """Strict word-number grammar. 'twenty five' -> 25. 'twenty five fifty' -> None."""
    if not tokens:
        return None
    total = 0
    current = 0
    state = "start"
    for tok in tokens:
        if tok in _TENS:
            if state in ("tens", "ones"):
                return None
            current += _TENS[tok]
            state = "tens"
        elif tok in _ONES:
            if state == "ones" or (state == "tens" and _ONES[tok] >= 10):
                return None
            current += _ONES[tok]
            state = "ones"
        elif tok == "hundred":
            if state == "scale":
                return None
            current = (current or 1) * 100
            state = "scale"
        elif tok in _SCALES:
            if state == "scale" and current == 0:
                return None
            total += (current or 1) * _SCALES[tok]
            current = 0
            state = "scale"
        else:
            return None
    return total + current


def parse_whole_dollars(text):
    """Spoken or typed amount -> int dollars >= 1, or None.

    Accepts "one dollar", "five bucks", "$3", "10", "ten dollars", "a dollar",
    "twenty five". Rejects anything with cents ("a dollar fifty", "2.50"),
    zero, negatives, run-on numbers ("twenty five fifty"), and no number.
    """
    if text is None:
        return None
    t = str(text).lower().strip()
    if not t:
        return None
    t = t.replace("$", " ").replace(",", "")
    if re.search(r"(^|\s)-\s*\d", t):
        return None                                  # negative
    t = re.sub(r"[^a-z0-9.\s-]", " ", t).replace("-", " ")
    if re.search(r"\bcents?\b", t) or re.search(r"\d\.\d", t) or re.search(r"\bhalf\b|\bquarter\b", t):
        return None
    t = t.replace(".", " ")
    tokens = t.split()
    if not tokens:
        return None
    # "a dollar" / "a buck" -> 1
    if tokens[0] in _ARTICLE_ONE and len(tokens) >= 2 and tokens[1] in ("dollar", "buck"):
        rest = [w for w in tokens[2:] if w not in _FILLER]
        return 1 if not rest else None
    tokens = [w for w in tokens if w not in _FILLER]
    if not tokens:
        return None
    if len(tokens) == 1 and re.fullmatch(r"\d+", tokens[0]):
        n = int(tokens[0])
        return n if n >= 1 else None
    if any(re.fullmatch(r"\d+", w) for w in tokens):
        return None                                  # mixed digits and words
    n = _words_to_number(tokens)
    return n if n is not None and n >= 1 else None


def whole_dollars_or_default(value, default=DEFAULT_BUY_USD):
    """Settings value -> int dollars. Anything not a whole dollar >= 1 falls back."""
    n = parse_whole_dollars(value)
    return n if n is not None else default


def parse_slippage_bps(value, default=DEFAULT_SLIPPAGE_BPS):
    try:
        n = int(str(value).strip())
    except (TypeError, ValueError):
        return default
    return n if MIN_SLIPPAGE_BPS <= n <= MAX_SLIPPAGE_BPS else default


def route_or_default(name):
    name = str(name or "").strip().lower()
    return name if name in ROUTES else DEFAULT_ROUTE


# -----------------------------------------------------------------------------
# Spoken numbers
# -----------------------------------------------------------------------------

def _int_words(n):
    if n == 0:
        return "zero"
    if n < 20:
        return [k for k, v in _ONES.items() if v == n and k != "oh"][0]
    if n < 100:
        tens = [k for k, v in _TENS.items() if v == n - n % 10][0]
        return tens if n % 10 == 0 else "%s-%s" % (tens, _int_words(n % 10))
    if n < 1000:
        rest = n % 100
        return "%s hundred" % _int_words(n // 100) + (" %s" % _int_words(rest) if rest else "")
    rest = n % 1000
    return "%s thousand" % _int_words(n // 1000) + (" %s" % _int_words(rest) if rest else "")


def dollars_words(n):
    n = int(n)
    return "%s dollar%s" % (_int_words(n), "" if n == 1 else "s")


def token_words(amount, name="Fartcoin"):
    """'about seven point four one Fartcoin' - 4 significant digits, digits spoken
    one at a time after the point so TTS can't slur them."""
    try:
        d = Decimal(str(amount))
    except (InvalidOperation, ValueError):
        return "some %s" % name
    if d <= 0:
        return "zero %s" % name
    sig = 4
    q = Decimal(1).scaleb(d.adjusted() - sig + 1)
    d = d.quantize(q, rounding=ROUND_DOWN)
    s = format(d.normalize(), "f")
    if "." in s:
        whole, frac = s.split(".")
        spoken = "%s point %s" % (_int_words(int(whole)), " ".join(_int_words(int(c)) for c in frac))
    else:
        spoken = _int_words(int(s))
    return "about %s %s" % (spoken, name)


# -----------------------------------------------------------------------------
# Requests
# -----------------------------------------------------------------------------

def build_quote_request(route, usd, slippage_bps=DEFAULT_SLIPPAGE_BPS):
    """The body for /wallet/swap-quote. `usd` must be a whole number >= 1."""
    r = ROUTES[route_or_default(route)]
    n = int(usd)
    if n < 1:
        raise ValueError("usd must be a whole number of dollars >= 1")
    return {
        "fromChain": r["fromChain"],
        "fromToken": r["fromToken"],
        "toChain": r["toChain"],
        "toToken": r["toToken"],
        "amount": str(n),
        "slippageBps": parse_slippage_bps(slippage_bps),
    }


_IDEMPOTENCY_NS = uuid.UUID("6f6a7274-6661-7274-3266-617274636f69")   # "fart2fartcoi" in hex


def idempotency_key(event_id):
    """Bankr requires a UUID. Derive one deterministically from the fart event id
    so a retry or a replayed event always presents the same key."""
    return str(uuid.uuid5(_IDEMPOTENCY_NS, str(event_id)))


def build_swap_request(quote_req, quote, event_id):
    """The body for /wallet/swap. quoteId is sent but Bankr ignores it cross-chain."""
    body = dict(quote_req)
    body["minBuyAmount"] = str(quote.get("minBuyAmount"))
    if quote.get("quoteId"):
        body["quoteId"] = quote["quoteId"]
    body["idempotencyKey"] = idempotency_key(event_id)
    return body


def _headers(key):
    return {"X-API-Key": key, "Content-Type": "application/json"}


def _safe_json(resp):
    try:
        return resp.json()
    except ValueError:
        return {"error": (resp.text or "")[:300]}


def bankr_swap_quote(read_key, quote_req):
    r = requests.post(BANKR_API + "/wallet/swap-quote", headers=_headers(read_key),
                      json=quote_req, timeout=QUOTE_TIMEOUT_S)
    return r.status_code, _safe_json(r)


def bankr_swap(trade_key, swap_req):
    r = requests.post(BANKR_API + "/wallet/swap", headers=_headers(trade_key),
                      json=swap_req, timeout=SWAP_TIMEOUT_S)
    return r.status_code, _safe_json(r)


def bankr_portfolio(read_key, chain, getter=None):
    """GET /wallet/portfolio for one chain. `getter` defaults to requests.get;
    the daemon passes worker.session_tasks.get because the upload scan rejects
    a literal requests.get in cloud files."""
    getter = getter or requests.get
    r = getter(BANKR_API + "/wallet/portfolio", headers=_headers(read_key),
               params={"chains": chain, "showLowValueTokens": "true"}, timeout=PORTFOLIO_TIMEOUT_S)
    return r.status_code, _safe_json(r)


# -----------------------------------------------------------------------------
# Responses
# -----------------------------------------------------------------------------

def _msg(body):
    if isinstance(body, dict):
        return str(body.get("error") or body.get("message") or "").lower()
    return ""


def quote_ok(status_code, body):
    return status_code == 200 and isinstance(body, dict) and body.get("minBuyAmount") is not None


def quote_error_reason(status_code, body):
    m = _msg(body)
    if status_code == 400:
        if "small" in m:
            return "That amount is too small for Bankr to trade."
        if "solana" in m and "address" in m:
            return "The Bankr wallet has no Solana address yet. Enable it on bankr dot bot."
        if "unsupported" in m or "untradable" in m:
            return "Bankr can't trade that pair right now."
        return "Bankr couldn't quote that."
    if status_code == 401:
        return "Bankr rejected the read key. Check it in Settings."
    if status_code == 403:
        return "Bankr won't quote Fartcoin right now."
    if status_code == 502:
        return "No bridge route right now. Skipped."
    return "I couldn't get a price from Bankr."


def map_execute_result(status_code, body):
    """/wallet/swap response -> (status, spoken).

    status: filled | reverted | blocked | refused | busy | unknown | error
      filled    success true + hash. Solana leg may still be in flight.
      blocked   Bankr spend limit. Caller sets blocked_today.
      refused   misconfiguration or funds; caller announces once per session.
      busy      409/429; skip this event, no retry.
      unknown   504 / timeout; caller reconciles via portfolio.
    """
    m = _msg(body)
    if status_code == 200:
        if isinstance(body, dict) and body.get("success") is True and body.get("hash"):
            return "filled", None
        return "reverted", "The buy reverted on chain. Nothing spent, apart from a little gas."
    if status_code == 504:
        return "unknown", "Not sure that one went through. I'll check."
    if status_code == 403:
        if "impact" in m:
            return "refused", "The price would move too much right now. Skipped."
        if "spend" in m or "limit" in m:
            return "blocked", "Bankr's spending limit stopped this one."
        if "paused" in m:
            return "refused", "The Bankr wallet is paused."
        if "read" in m:
            return "refused", "The trade key is read-only. Check the key settings on bankr dot bot."
        if "location" in m:
            return "refused", "Bankr blocked the trade key's location."
        return "refused", "Bankr declined the trade."
    if status_code == 400:
        if "gas" in m:
            return "refused", "The wallet is out of gas on Base."
        if "balance" in m or "insufficient" in m:
            return "refused", "The wallet is out of dollars on Base."
        if "impact" in m:
            return "refused", "The price would move too much right now. Skipped."
        return "refused", "Bankr couldn't place the trade."
    if status_code == 409:
        return "busy", None
    if status_code == 429:
        return "busy", "Bankr is busy. Skipped."
    if status_code == 502:
        return "error", "No bridge route right now. Skipped."
    if status_code in (500, 503):
        return "error", "Bankr had a problem placing the trade."
    return "error", "Bankr returned an unexpected response."


def _dec(x):
    try:
        return Decimal(str(x))
    except (InvalidOperation, ValueError, TypeError):
        return Decimal(0)


def fartcoin_balance(portfolio):
    """Fartcoin token balance on Solana from a /wallet/portfolio body, as Decimal.
    Tolerant of the Base-shaped schema (baseToken.address) and a flat one (address/mint)."""
    chain = ((portfolio or {}).get("balances") or {}).get("solana") or {}
    for entry in chain.get("tokenBalances") or []:
        tok = (entry or {}).get("token") or entry or {}
        base = tok.get("baseToken") or {}
        addr = str(base.get("address") or tok.get("address") or tok.get("mint") or "")
        if addr == FARTCOIN_MINT:
            return _dec(tok.get("balance"))
    return Decimal(0)


def usdc_balance(portfolio, chain):
    """USDC balance on `chain` from a /wallet/portfolio body, as Decimal."""
    want = {"base": USDC_BASE.lower(), "solana": USDC_SOLANA}.get(chain)
    c = ((portfolio or {}).get("balances") or {}).get(chain) or {}
    for entry in c.get("tokenBalances") or []:
        tok = (entry or {}).get("token") or entry or {}
        base = tok.get("baseToken") or {}
        addr = str(base.get("address") or tok.get("address") or tok.get("mint") or "")
        if addr == want or addr.lower() == want:
            return _dec(tok.get("balance"))
    return Decimal(0)


def native_balance(portfolio, chain):
    c = ((portfolio or {}).get("balances") or {}).get(chain) or {}
    return _dec(c.get("nativeBalance"))


def is_valid_route(route):
    r = ROUTES.get(route)
    if not r:
        return False
    ok_from = _EVM_ADDR_RE.match(r["fromToken"]) if r["fromChain"] != "solana" else _BASE58_RE.match(r["fromToken"])
    return bool(ok_from and _BASE58_RE.match(r["toToken"]))


# -----------------------------------------------------------------------------
# Journal (a list of dicts kept in the KV store by the daemon)
# -----------------------------------------------------------------------------

def journal_entry(event, usd, route, status, mode, **extra):
    e = {"event_id": event.get("id"), "ts": event.get("ts"), "usd": str(int(usd)),
         "route": route, "status": status, "mode": mode}
    e.update(extra)
    return e


def append_journal(journal, entry):
    j = list(journal or [])
    j.append(entry)
    return j[-JOURNAL_MAX:]


def update_journal(journal, event_id, **changes):
    out = []
    for e in journal or []:
        if e.get("event_id") == event_id:
            e = {**e, **changes}
        out.append(e)
    return out


def pending_arrivals(journal):
    return [e for e in journal or [] if e.get("status") in ("filled", "in_transit", "unknown")]


def day_key(ts):
    """UTC day bucket for a unix timestamp. Kept simple: the daily report is
    'since midnight UTC', which is fine for a toy and avoids tz plumbing."""
    return int(float(ts or 0) // 86400)


def report_line(journal, today_key, mode):
    today = [e for e in journal or [] if day_key(e.get("ts")) == today_key]
    if mode != "live":
        return "Fart trading is in dry run. Nothing has been bought."
    if not today:
        return "No Fartcoin bought today."
    bought = [e for e in today if e.get("status") in ("filled", "landed", "in_transit")]
    blocked = [e for e in today if e.get("status") == "blocked"]
    spent = sum(int(e.get("usd", 0)) for e in bought)
    tokens = sum((_dec(e.get("tokens")) for e in bought), Decimal(0))
    n = len(bought)
    parts = ["%s fart%s bought %s of Fartcoin today" % (_int_words(n).capitalize(), "" if n == 1 else "s", dollars_words(spent))]
    if tokens > 0:
        parts.append("That's %s" % token_words(tokens))
    if blocked:
        parts.append("%s more %s stopped by your Bankr limit" % (_int_words(len(blocked)), "was" if len(blocked) == 1 else "were"))
    in_transit = [e for e in bought if e.get("status") == "in_transit"]
    if in_transit:
        parts.append("%s still in transit" % _int_words(len(in_transit)))
    return ". ".join(parts) + "."


def dumps(obj):
    return json.dumps(obj, separators=(",", ":"), default=str)
# ---- end trade.py ----


def unwrap_reply(raw):
    """Device replies arrive in transport envelopes, e.g. Local Link:
    {'type':'response','data':{'status':'ok','data':'<json>'}}. Descend through
    'data' until a dict with 'ok' or a JSON string is found."""
    for _ in range(6):
        if isinstance(raw, dict):
            if "ok" in raw:
                return raw
            if "data" in raw:
                raw = raw["data"]
                continue
            if "result" in raw:
                raw = raw["result"]
                continue
            return {"ok": False, "error": "unrecognised device reply"}
        if isinstance(raw, str):
            text = raw.strip()
            for line in reversed(text.splitlines()):
                line = line.strip()
                if line.startswith("{"):
                    try:
                        raw = json.loads(line)
                        break
                    except ValueError:
                        continue
            else:
                return {"ok": False, "error": "unparseable device reply: %s" % text[:200]}
            continue
        return {"ok": False, "error": "empty device reply"}
    return {"ok": False, "error": "device reply nested too deep"}


def say_number(x):
    x = round(float(x), 1)
    whole = int(x)
    tenth = int(round((x - whole) * 10))
    w = "ten" if whole == 10 else ONES[whole] if whole < 10 else str(whole)
    return w if tenth == 0 else "%s point %s" % (w, ONES[tenth])


def announcement(event):
    lead, advice = CLASS_LINES.get(event.get("class"), CLASS_LINES["standard-issue"])
    return " ".join([lead,
                     "Magnitude %s." % say_number(event.get("magnitude", 4.0)),
                     "Duration %s seconds." % say_number(event.get("duration_s", 0.5)),
                     advice])


class Fart2FartcoinBackground(MatchingCapability):
    worker: AgentWorker = None
    capability_worker: CapabilityWorker = None
    background_daemon_mode: bool = False

    # Do not change following tag of register capability
    #{{register capability}}

    # ------------------------------------------------------------ settings
    _file_settings = None

    async def _load_file_settings(self):
        """settings.local.json in the ability folder, for dev without the dashboard."""
        if self._file_settings is not None:
            return
        self._file_settings = {}
        try:
            if await self.capability_worker.check_if_file_exists(SETTINGS_FILE, True):
                raw = await self.capability_worker.read_file(SETTINGS_FILE, True)
                data = json.loads(raw or "{}")
                if isinstance(data, dict):
                    self._file_settings = data
        except Exception as e:
            self._log("settings file: %r" % (e,))

    def _setting(self, name, default=""):
        """Settings -> API Keys wins, then settings.local.json, then default."""
        try:
            v = self.capability_worker.get_api_keys(name)
            if v:
                return v
        except Exception:
            pass
        v = (self._file_settings or {}).get(name)
        return str(v) if v not in (None, "") else default

    def _log(self, msg):
        self.worker.editor_logging_handler.info("[Fart2Fart(coin)] %s" % msg)

    # ----------------------------------------------------------- transport
    async def _call_device(self, fn, args=None):
        args = [str(a) for a in (args or [])]
        transport = self._setting("fartfinder_transport", "devkit").strip().lower()
        try:
            if transport == "local":
                prefix = self._setting("fartfinder_local_cmd", "")
                if not prefix:
                    return {"ok": False, "error": "fartfinder_local_cmd not set"}
                cmd = " ".join([prefix, fn] + ["'%s'" % a.replace("'", "'\\''") for a in args])
                raw = await self.capability_worker.exec_local_command(cmd, timeout=LOCAL_TIMEOUT_S)
            else:
                raw = await self.capability_worker.send_devkit_capability_action(fn, args, DEVICE_TIMEOUT_S)
        except Exception as e:
            return {"ok": False, "error": "transport: %r" % (e,)}
        parsed = self._parse(raw)
        if not parsed.get("ok"):
            self._log("device %s failed: %r raw=%r" % (fn, parsed.get("error"), str(raw)[:160]))
        return parsed

    def _parse(self, raw):
        return unwrap_reply(raw)

    # ------------------------------------------------------------- consent
    def _state(self):
        try:
            v = self.capability_worker.get_single_key(CONTEXT_KEY)
            if isinstance(v, str):
                try:
                    v = json.loads(v)
                except ValueError:
                    return {}
            if isinstance(v, dict) and "value" in v:
                v = v["value"]            # {'key': ..., 'value': {...}} or value None when missing
            if isinstance(v, str):
                try:
                    v = json.loads(v)
                except ValueError:
                    return {}
            return v if isinstance(v, dict) else {}
        except Exception as e:
            self._log("state read failed: %r" % (e,))
            return {}

    def _save_state(self, state):
        try:
            if self._state():
                r = self.capability_worker.update_key(CONTEXT_KEY, state)
            else:
                r = self.capability_worker.create_key(CONTEXT_KEY, state)
            if not (isinstance(r, dict) and r.get("success", True)):
                self._log("state save rejected: %r" % (r,))
        except Exception as e:
            self._log("state save failed: %r" % (e,))

    async def _wait_for_consent(self):
        """A daemon must never await user input (it never gets control back),
        so consent is recorded by the skill's "arm" intent. Announce once,
        then poll the stored state."""
        state = self._state()
        if state.get("consent") == "yes":
            return
        if not state.get("notified"):
            await self.capability_worker.send_interrupt_signal()
            await self.capability_worker.speak(NOT_ARMED_NOTICE)
            self._save_state({**state, "notified": True})
        while self._state().get("consent") != "yes":
            await self.worker.session_tasks.sleep(CONSENT_POLL_S)
        self._log("consent recorded; starting")

    # --------------------------------------------------------------- hooks
    async def _run_hooks(self, event):
        hooks = [h.strip() for h in self._setting("fartfinder_hooks", "speak,buy").split(",") if h.strip()]
        for h in hooks:
            try:
                if h == "speak":
                    await self._call_device("mute", [4])
                    await self.capability_worker.send_interrupt_signal()
                    await self.capability_worker.speak(announcement(event))
                elif h == "webhook":
                    url = self._setting("fartfinder_webhook_url", "")
                    if url:
                        import requests
                        requests.post(url, json=event, timeout=5)
                elif h == "led":
                    await self._call_device("led_flash", [event.get("class", "standard-issue")])
                elif h == "buy":
                    if not event.get("near_miss"):
                        await self._buy(event)
            except Exception as e:
                self._log("hook %s failed: %r" % (h, e))

    # ---------------------------------------------------------------- trading
    _announced = None          # once-per-session notices already spoken

    def _trading(self):
        """Effective trading config: KV (set by voice) wins over Settings."""
        st = self._state()
        mode = st.get("mode") or self._setting("fart2fart_mode", "dry_run")
        mode = "live" if str(mode).strip().lower() == "live" else "dry_run"
        usd = whole_dollars_or_default(st.get("buy_usd") or self._setting("fart2fart_buy_usd", ""))
        route = route_or_default(st.get("route") or self._setting("fart2fart_route", ""))
        slip = parse_slippage_bps(self._setting("fart2fart_slippage_bps", ""))
        return {"mode": mode, "usd": usd, "route": route, "slippage": slip,
                "read_key": self._setting(READ_KEY_NAME, ""),
                "trade_key": self._setting(TRADE_KEY_NAME, "")}

    async def _speak(self, text):
        await self._call_device("mute", [4])
        await self.capability_worker.send_interrupt_signal()
        await self.capability_worker.speak(text)

    async def _speak_once(self, key, text):
        if self._announced is None:
            self._announced = set()
        if key in self._announced:
            return
        self._announced.add(key)
        await self._speak(text)

    def _journal(self, entry=None, event_id=None, **changes):
        st = self._state()
        j = st.get("journal") or []
        if entry is not None:
            j = append_journal(j, entry)
        if event_id is not None:
            j = update_journal(j, event_id, **changes)
        st["journal"] = j
        self._save_state(st)
        return st

    async def _buy(self, event):
        cfg = self._trading()
        st = self._state()
        eid = str(event.get("id", ""))
        if eid and eid <= str(st.get("last_traded_id") or ""):
            self._log("skip %s: at or below last_traded_id" % eid)
            return
        if not cfg["read_key"]:
            await self._speak_once("nokey", "Fart2Fart(coin) has no Bankr read key. Add bankr_read_key in Settings.")
            return
        dollars = dollars_words(cfg["usd"])
        if cfg["mode"] != "live":
            code, q = await asyncio.to_thread(bankr_swap_quote, cfg["read_key"],
                                              build_quote_request(cfg["route"], cfg["usd"], cfg["slippage"]))
            if quote_ok(code, q):
                await self._speak(DRY_RUN_LINE % (dollars, token_words((q.get("to") or {}).get("formattedAmount") or q.get("minBuyAmount"))))
            else:
                self._log("dry-run quote %s %s" % (code, json.dumps(q)[:200]))
                await self._speak(DRY_RUN_NO_QUOTE % dollars)
            self._journal(journal_entry(event, cfg["usd"], cfg["route"], "dry_run", "dry_run"))
            return
        if not cfg["trade_key"]:
            await self._speak_once("notradekey", "Fart trading is on but there is no Bankr trade key. Nothing bought.")
            return
        if st.get("blocked_day") == day_key(time()):
            self._log("skip %s: Bankr limit already hit today" % eid)
            self._journal(journal_entry(event, cfg["usd"], cfg["route"], "blocked", "live"))
            return

        quote_req = build_quote_request(cfg["route"], cfg["usd"], cfg["slippage"])
        code, q = await asyncio.to_thread(bankr_swap_quote, cfg["read_key"], quote_req)
        if not quote_ok(code, q):
            self._log("quote failed %s %s" % (code, json.dumps(q)[:300]))
            self._journal(journal_entry(event, cfg["usd"], cfg["route"], "failed", "live", stage="quote", http=code))
            await self._speak(quote_error_reason(code, q))
            return
        swap_req = build_swap_request(quote_req, q, eid)
        self._log("swap %s usd=%s route=%s" % (eid, cfg["usd"], cfg["route"]))
        try:
            code, body = await asyncio.to_thread(bankr_swap, cfg["trade_key"], swap_req)
        except Exception as e:
            self._log("swap transport error: %r" % (e,))
            code, body = 504, {"error": "timeout"}
        status, spoken = map_execute_result(code, body)
        self._log("swap %s -> %s %s %s" % (eid, code, status, json.dumps(body)[:300]))
        st = self._state()
        entry = journal_entry(event, cfg["usd"], cfg["route"], status, "live", http=code)
        if status == "filled":
            entry["hash"] = body.get("hash")
            entry["tokens"] = str(body.get("amountReceived") or "")
            entry["filled_ts"] = round(time(), 1)
            st["last_traded_id"] = eid
            st["journal"] = append_journal(st.get("journal"), entry)
            self._save_state(st)
            await self._speak(BOUGHT_LINE % (dollars, token_words(entry["tokens"])))
            return
        if status == "blocked":
            st["blocked_day"] = day_key(time())
        if status == "unknown":
            entry["filled_ts"] = round(time(), 1)
            st["last_traded_id"] = eid            # never re-buy something that may be on chain
        st["journal"] = append_journal(st.get("journal"), entry)
        self._save_state(st)
        if status == "refused":
            await self._speak_once("refused:%s" % spoken, spoken)
        elif spoken:
            await self._speak(spoken)

    _last_arrival_check = 0.0

    async def _check_arrivals(self):
        """Resolve filled/unknown entries by watching the Solana Fartcoin balance."""
        if time() - self._last_arrival_check < ARRIVAL_CHECK_EVERY_S:
            return
        self._last_arrival_check = time()
        st = self._state()
        pending = pending_arrivals(st.get("journal"))
        if not pending:
            return
        cfg = self._trading()
        if not cfg["read_key"]:
            return
        try:
            code, body = await asyncio.to_thread(bankr_portfolio, cfg["read_key"], "solana",
                                                 self.worker.session_tasks.get)
        except Exception as e:
            self._log("portfolio: %r" % (e,))
            return
        if code != 200:
            self._log("portfolio %s %s" % (code, json.dumps(body)[:200]))
            return
        bal = fartcoin_balance(body)
        prev = _dec(st.get("last_fartcoin_balance"))
        st = self._state()
        changed = False
        if bal > prev:
            # Oldest pending entries land first; attribute the rise to them in order.
            gained = bal - prev
            for e in sorted(pending, key=lambda x: x.get("filled_ts") or 0):
                if gained <= 0:
                    break
                want = _dec(e.get("tokens")) or gained
                st["journal"] = update_journal(st.get("journal"), e["event_id"], status="landed",
                                                     landed_ts=round(time(), 1),
                                                     tokens=str(e.get("tokens") or gained))
                gained -= want
                changed = True
                if e.get("status") == "unknown":
                    await self._speak(LANDED_LATE_LINE)
        for e in pending_arrivals(st.get("journal")):
            age = time() - float(e.get("filled_ts") or time())
            if age > ARRIVAL_WINDOW_S and e.get("status") != "in_transit":
                st["journal"] = update_journal(st.get("journal"), e["event_id"], status="in_transit")
                changed = True
                await self._speak_once("notlanded:%s" % e["event_id"], NOT_LANDED_LINE)
        st["last_fartcoin_balance"] = str(bal)
        self._save_state(st)
        if changed:
            self._log("arrivals: balance %s -> %s" % (prev, bal))

    async def _daily_line(self):
        st = self._state()
        today = day_key(time())
        if st.get("reported_day") == today:
            return
        yesterday = today - 1
        cfg = self._trading()
        if st.get("reported_day") is not None and cfg["mode"] == "live":
            line = report_line(st.get("journal"), yesterday, "live")
            if not line.startswith("No Fartcoin"):
                await self._speak(DAILY_LINE % line.rstrip("."))
        st["reported_day"] = today
        self._save_state(st)

    # ---------------------------------------------------------------- loop
    async def watch(self):
        self._log("daemon starting at %s" % time())
        await self._load_file_settings()
        self._log("transport=%s" % self._setting("fartfinder_transport", "devkit"))
        await self._wait_for_consent()
        since = "0"
        last_restart = 0.0
        first = True
        while True:
            try:
                if first:
                    self._log("calling start_listener via %s" % self._setting("fartfinder_transport", "devkit"))
                    r = await self._call_device("start_listener", ["{}"])
                    self._log("start_listener -> %s" % json.dumps(r)[:200])
                    first = False
                    last_restart = time()
                    # Fast-forward past anything logged before this session so
                    # old events are not announced at session start.
                    r = await self._call_device("poll_events", ["0"])
                    if r.get("ok") and r.get("events"):
                        since = r["events"][-1]["id"]
                        self._log("skipping %d earlier event(s) from today" % len(r["events"]))
                        st = self._state()
                        if since > str(st.get("last_traded_id") or ""):
                            st["last_traded_id"] = since      # a redeploy must never replay buys
                            self._save_state(st)
                    await self.worker.session_tasks.sleep(POLL_INTERVAL_S)
                    continue
                r = await self._call_device("poll_events", [since])
                if not r.get("ok") or not r.get("daemon_alive", True):
                    if time() - last_restart > RESTART_BACKOFF_S:
                        self._log("listener down (%s); restarting" % r.get("error"))
                        await self._call_device("start_listener", ["{}"])
                        last_restart = time()
                else:
                    for ev in r.get("events", []):
                        if ev.get("id", "") <= since:
                            continue
                        since = ev["id"]
                        self._log("EVENT %s" % json.dumps(ev))
                        await self._run_hooks(ev)
                    since = max(since, r.get("last_id", since) or since)
                await self._check_arrivals()
                await self._daily_line()
            except Exception as e:
                self._log("loop error: %r" % (e,))
            await self.worker.session_tasks.sleep(POLL_INTERVAL_S)

    def call(self, worker: AgentWorker, background_daemon_mode: bool):
        self.worker = worker
        self.background_daemon_mode = background_daemon_mode
        self.capability_worker = CapabilityWorker(self)
        self.worker.session_tasks.create(self.watch())
